language: go

go:
  - 1.10.x
  - 1.12.x
  - 1.14.x

env:
  global:
      - PGHOST=127.0.0.1
  matrix:
      - PGVERSION=10
      - PGVERSION=9.6

  before_script:
    - createdb test

script: go get github.com/prajwalpatil2505/nzgo_prajwal && go build && go test ./...
